---
config:
  themeVariables:
    xyChart:
      plotColorPalette: "#000000"
  theme: base
  look: classic
---
xychart-beta
    x-axis "Number of peers" 2 --> 7
    y-axis "Number of training rounds" 1 --> 30
    line [9,7,16,16,16,23]
