---
config:
  themeVariables:
    xyChart:
      plotColorPalette: "#000000"
  theme: base
  look: classic
---
xychart-beta
    x-axis "Number of peers" 1 --> 7
    y-axis "Number of training rounds" 1 --> 30
    line [2,3,5,9,15,21,29]
