---
config:
  theme: base
  look: classic
---
stateDiagram-v2
    [*] --> Setup

    Setup --> Executing : connected to peers / received starting model
    state Executing {
        [*] --> Training
        Training --> SecureAverageComputation : training step complete
        SecureAverageComputation --> Training : model not complete
        SecureAverageComputation --> [*] : model complete
    }
    Executing --> Aborting : peer failure detected
    Executing --> SavingModel : execution completed
    SavingModel --> [*] : model saved
    Aborting --> [*]
    Shutdown --> [*]

