from enum import Enum

class State(Enum):
    CONNECTING = "CONNECTING"
    SETUP = "SETUP"
    TRAINING = "TRAINING"
    SECURE_AVERAGE_COMPUTATION = "SECURE_AVERAGE_COMPUTATION"
    SAVING_MODEL = "SAVING_MODEL"
    TERMINATION_CHECK = "TERMInatioN_CHECK"
    SHUTDOWN = "SHUTDOWN"

